### PR TITLE
Update to 1.17.1 Attempt 2

### PR DESCRIPTION
**Pull request by NoComment1105**

### CODE REVIEW

**Comment by reoseah** [comment]
Oh, I completely forgot about this! Really sorry ^^'

I'll see it in a moment

**Comment by reoseah** [comment]
Looks good to me, I can't really test it now since mod for which I wanted this functionality was abandoned and deleted long ago...

**Comment by NoComment1105** [comment]
> Looks good to me, I can't really test it now since mod for which I wanted this functionality was abandoned and deleted long ago...

You can see [my mod](https://github.com/NoComment1105/DeepslateCutting-fabric) where it works perfectly @Reoseah

**Comment by reoseah** [comment]
Well, I'm glad you found it useful. I believe most mods with optional blocks or items generate json on runtime, e.g. natanfudge/artifice, although it also seems to be abandoned...

**Pull request merged**
